package vistas;

import components.styles.Theme;
import javax.swing.JPanel;
import modelos.Usuario;

/**
 *
 * @author Johan
 */
public class BarraApp extends javax.swing.JPanel {
    /**
     * Creates new form BarraApp
     */
    public BarraApp(){
        this(null);
    }
    
    public BarraApp(Object usuario){
        initComponents();
        if(usuario != null){
            add(new BarraLoggedIn());
        }else{
            add(new BarraLoggedOut());
        }
        
    }
    
    protected void iniciarSesion(Usuario usuario){
        pintarBarra(new BarraLoggedIn(usuario));
    }
    
    protected void cerrarSesion(){
        pintarBarra(new BarraLoggedOut());
    }
    
    private void pintarBarra(JPanel barra){
        removeAll();
        add(barra);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(Theme.PRIMARY);
        setPreferredSize(new java.awt.Dimension(157, 40));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
