package vistas;

import components.menus.NavBarItem;
import components.surfaces.Card;
import controladores.ControlTema;
import controladores.listas.ListaTemas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import modelos.Recurso;
import modelos.Tema;

/**
 *
 * @author Johan Romero
 */
public class Inicio extends javax.swing.JFrame {
    public String motorDB;
    private ControlTema controlTema;
    private JPopupMenu popupBusqueda;
    /**
     * Creates new form Main
     */
    public Inicio() {
        this("MySQL");
    }
    
    public Inicio(String motorDB){
        initComponents();
        
        this.motorDB = motorDB;
        controlTema = new ControlTema(motorDB);
        
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        
        busqueda.setPlaceholder("Buscar");
        busqueda.requestFocus();
        
        popupBusqueda = new JPopupMenu();
        popupBusqueda.setBackground(Color.white);
    }

    @Override
    public void setVisible(boolean b) {
        try {
            busqueda.setText("");
            busqueda.requestFocus();
            mostrarConsultados();
        } catch (Exception ex) {
            b = false;
        }
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void mostrarConsultados() throws Exception{
        try{
            ListaTemas temas = controlTema.obtenerMasConsultados();
            if(temas.getLength() > 0){
                panelCartas.removeAll();
                for(int i = 0; i < temas.getLength(); i++){
                    Tema tema = temas.obtener(i);
                    Recurso recurso = tema.getRecursos().obtener(0);
                    Card carta = new Card();
                    carta.setTitle(tema.getTitulo());
                    carta.setContent(tema.getDescripcion());
                    carta.setImage(recurso.getRuta());
                    carta.link.setText("Ver más");
                    //Evento del link de la carta
                    carta.link.addMouseListener(new MouseAdapter(){
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            mostrarInterfazTema(tema.getId());
                        }
                        
                    });
                    panelCartas.add(carta);
                }
                setSize(new Dimension(941, 666));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            throw ex;
        }
    }
    
    private void mostrarInterfazTema(int id){
        try {
            informacion tema_info = new informacion(this, controlTema.TemasAmostrar(id));
            setVisible(false);
            tema_info.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado el tema");
        }
    }
    
    private void limpiarPopupBusqueda(){
        popupBusqueda.setVisible(false);
        popupBusqueda.removeAll();
    }
    
    private JMenuItem getSearchItem(Tema tema){
        JMenuItem item = new NavBarItem(tema.getTitulo());
        item.addActionListener(e -> busqueda.setText(item.getText()));
        item.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    busqueda.setText(item.getText());
                }
            }
        });
        
        return item;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCartas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new components.buttons.PrimaryButton();
        busqueda = new components.inputs.TextInput();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        barraApp1 = new vistas.BarraApp();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compuwiki");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panelCartas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        panelCartas.setOpaque(false);
        panelCartas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 32, 5));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Temas no encontrados");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 0, 32, 0));
        panelCartas.add(jLabel2);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/search_white.png"))); // NOI18N
        btnBuscar.setText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setText("Más consultados");

        titulo.setFont(new java.awt.Font("SansSerif", 0, 56)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Compuwiki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraApp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(barraApp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(titulo)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyReleased
        // TODO add your handling code here:
        //if(!evt.isActionKey()) limpiarPopupBusqueda(); 
        
        String text = busqueda.getText().trim();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) return;
        limpiarPopupBusqueda();
        if(!text.isEmpty()){
            try{
                ListaTemas temas = controlTema.buscarTitulos(text);
                if(temas.getLength() > 0){
                    for(int i = 0; i < temas.getLength(); i++){
                        popupBusqueda.add(getSearchItem(temas.obtener(i)));
                    }
                    popupBusqueda.show(busqueda, 0, busqueda.getHeight());
                }
                
            }catch(Exception ex){
                System.out.println(ex.toString());
            }
        }
        if(!evt.isActionKey())busqueda.requestFocus();
    }//GEN-LAST:event_busquedaKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String text = busqueda.getText().trim();
        if(!text.isEmpty()){
            try{
                int id = controlTema.obtenerId(text);
                if(id > 0){
                    mostrarInterfazTema(id);
                }else{
                    throw new Exception("El tema "+text+" no fue encontrado");
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vistas.BarraApp barraApp1;
    private components.buttons.PrimaryButton btnBuscar;
    private components.inputs.TextInput busqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
